DROP DATABASE  IF EXISTS `mail_box_demo`;

CREATE DATABASE  IF NOT EXISTS `mail_box_demo`;
USE `mail_box_demo`;

--
-- Table structure for table `user`
--

DROP TABLE IF EXISTS `user`;

CREATE TABLE `USER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PASSWORD` CHAR(80) NOT NULL,
  `FIRST_NAME` VARCHAR(50) NOT NULL,
  `LAST_NAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


INSERT INTO `USER` (USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL)
VALUES 
('john','$2a$04$eFytJDGtjbThXa80FyOOBuFdK2IwjyWefYkMpiBEFlpBwDH.5PM0K','John','Doe','john@doe.com'),
('mary','$2a$04$eFytJDGtjbThXa80FyOOBuFdK2IwjyWefYkMpiBEFlpBwDH.5PM0K','Mary','Public','mary@public.com'),
('susan','$2a$04$eFytJDGtjbThXa80FyOOBuFdK2IwjyWefYkMpiBEFlpBwDH.5PM0K','Susan','Adams','susan@adams.com');

CREATE TABLE `ROLE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` INT(11) NOT NULL,
	`ROLE_NAME` VARCHAR(200) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_ROLE_USER_ID` (`USER_ID`),
	CONSTRAINT `FK_ROLE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
)
ENGINE=InnoDB;

INSERT INTO `ROLE` (USER_ID,ROLE_NAME)
VALUES 
((SELECT ID FROM USER WHERE USERNAME = 'john'),'ADMIN'),
((SELECT ID FROM USER WHERE USERNAME = 'john'),'EMPLOYEE'),
((SELECT ID FROM USER WHERE USERNAME = 'mary'),'EMPLOYEE'),
((SELECT ID FROM USER WHERE USERNAME = 'susan'),'EMPLOYEE');


CREATE TABLE `MESSAGE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`MAIL_BODY` LONGTEXT NOT NULL,
	`READ_STATUS` ENUM('Y','N') NOT NULL,
	`SUBJECT` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci';

CREATE TABLE `USER_MESSAGE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`SENDER_USER_ID` INT(11) NOT NULL,
	`RECEIVER_USER_ID` INT(11) NOT NULL,
	`MESSAGE_ID` INT(11) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `INDEX_SENDER_USER_ID` (`SENDER_USER_ID`),
	INDEX `INDEX_RECEIVER_USER_ID` (`RECEIVER_USER_ID`),
	INDEX `INDEX_MESSAGE_ID` (`MESSAGE_ID`),
	CONSTRAINT `FK_USER_MESSAGE_MESSAGE_ID` FOREIGN KEY (`MESSAGE_ID`) REFERENCES `MESSAGE` (`ID`),
	CONSTRAINT `FK_USER_MESSAGE_RECEIVER_USER_ID` FOREIGN KEY (`RECEIVER_USER_ID`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_USER_MESSAGE_SENDER_USER_ID` FOREIGN KEY (`SENDER_USER_ID`) REFERENCES `USER` (`ID`)
)
ENGINE=InnoDB;




